### ISSUE TITLE
Add a view for error

### ISSUE THREAD

**Issue by mrfanatic** [siralam/WebViewSuite#5]
Hi, WebViewSuite is great. It would be really nice if there is a view to hide the actual URL when there is an error or no connection, much like an empty list view.

**Comment by siralam** [comment]
Since the design will vary a lot on different projects, I personally suggest you do it by yourself; e.g. When a URL cannot be loaded (onPageLoadError), toggle visibility of the WebViewSuite and set your own error view visible. Therefore I am not going to implement a default one into the library.

Thanks for your suggestion though!
